spring:
  application:
    name: coupon

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:create}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
      cors:
        allowed-origins: ${FRONTEND_ORIGIN:http://localhost:3000}
        allowed-methods: GET

app:
  cors:
    allowed-origins: ${FRONTEND_ORIGIN:http://localhost:3000}


server:
  port: ${SERVER_PORT:8080}
